name: Checks
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check:
    name: PoC for govulncheck-action bug
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    -
      id: set-up-go
      name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache: true
    # suppose one wanted to do other things in the same job, besides just
    # running govulncheck
    -
      id: govulncheck
      uses: golang/govulncheck-action@7da72f730e37eeaad891fcff0a532d27ed737cd4
      with:
        go-version-file: 'go.mod'
        repo-checkout: false
